import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { api } from '../api'
import ExpenseForm from '../components/ExpenseForm'

function money(value, currency, hidden) { return hidden ? '****' : new Intl.NumberFormat('en-US', { style: 'currency', currency, maximumFractionDigits: 2 }).format(value) }
export default function Expenses({ user, hideAmounts }) {
  const [expenses, setExpenses] = useState([]); const [wallets, setWallets] = useState([]); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All categories'); const [moneyType, setMoneyType] = useState('All'); const [account, setAccount] = useState('All accounts'); const [rates, setRates] = useState({}); const [editing, setEditing] = useState(null); const [error, setError] = useState(''); const [params, setParams] = useSearchParams()
  const categories = ['All categories', 'Food', 'Transportation', 'Shopping', 'Bills', 'Entertainment', 'Health', 'Education', 'Other']; const moneyTypes = [['All', 'All money types'], ['cash', 'Cash'], ['bank', 'Bank'], ['ewallet', 'E-wallet'], ['digital-wallet', 'Digital Wallet']]
  useEffect(() => { api('/expenses').then(setExpenses).catch(err => setError(err.message)) }, [])
  useEffect(() => { api('/wallets').then(setWallets).catch(err => setError(err.message)) }, [])
  useEffect(() => { const currencies = [...new Set(expenses.map(item => item.currency || 'PHP'))].filter(currency => currency !== user.currency); Promise.all(currencies.map(currency => api(`/rates?from=${currency}&to=${user.currency}`).then(data => [currency, data.rate]).catch(() => [currency, null]))).then(entries => setRates(Object.fromEntries(entries))) }, [expenses, user.currency])
  useEffect(() => { if (params.get('add') === 'true') setEditing({ new: true }) }, [params])
  const visible = useMemo(() => expenses.filter(item => item.description.toLowerCase().includes(query.toLowerCase()) && (category === 'All categories' || item.category === category) && (moneyType === 'All' || item.moneyType === moneyType) && (account === 'All accounts' || item.account === account)), [expenses, query, category, moneyType, account])
  async function save(form) { try { const data = editing.new ? await api('/expenses', { method: 'POST', body: JSON.stringify(form) }) : await api(`/expenses/${editing._id}`, { method: 'PUT', body: JSON.stringify(form) }); setExpenses(current => editing.new ? [data, ...current] : current.map(item => item._id === data._id ? data : item)); close() } catch (err) { setError(err.message) } }
  async function remove(id) { if (!window.confirm('Delete this expense? This cannot be undone.')) return; try { await api(`/expenses/${id}`, { method: 'DELETE' }); setExpenses(current => current.filter(item => item._id !== id)) } catch (err) { setError(err.message) } }
  function close() { setEditing(null); if (params.get('add')) setParams({}) }
  const accounts = [...new Set(expenses.map(item => item.account).filter(Boolean))]
  return <><header className="page-header"><div><span className="eyebrow">Your ledger</span><h1>Expenses</h1><p className="muted">Keep every transaction and source in one place.</p></div><button className="button primary" onClick={() => setEditing({ new: true })}>+ Add expense</button></header>{error && <div className="alert error">{error}</div>}<section className="panel expenses-panel"><div className="filters"><label className="search"><span>⌕</span><input placeholder="Search expenses" value={query} onChange={e => setQuery(e.target.value)} /></label><select value={moneyType} onChange={e => setMoneyType(e.target.value)}>{moneyTypes.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={category} onChange={e => setCategory(e.target.value)}>{categories.map(item => <option key={item}>{item}</option>)}</select><select value={account} onChange={e => setAccount(e.target.value)}><option>All accounts</option>{accounts.map(item => <option key={item}>{item}</option>)}</select></div>{visible.length === 0 ? <div className="empty-state"><strong>{expenses.length ? 'No matches found.' : 'No expenses yet.'}</strong><span>{expenses.length ? 'Try a different search, money type, or account.' : 'Add your first expense and your history will appear here.'}</span></div> : <div className="expense-card-list">{visible.map(item => <article className="expense-card" key={item._id}><span className="category-icon"><CategoryIcon category={item.category} /></span><div className="expense-card-main"><div className="expense-card-title"><div><strong>{item.description}</strong><small>{item.category} · {item.account || 'No account selected'} · {new Date(item.date).toLocaleDateString()}</small></div><div className="amount-stack"><strong>{money(item.amount, item.currency || 'PHP')}</strong>{item.currency !== user.currency && rates[item.currency] && <small>≈ {money(item.amount * rates[item.currency], user.currency)}</small>}</div></div><div className="expense-card-meta"><span className="source-pill" style={{ '--source-accent': item.accountColor || '#667085' }}>{item.moneyType || 'cash'} · {item.account || 'Cash'}</span><div className="row-actions"><button onClick={() => setEditing(item)}>Edit</button><button onClick={() => remove(item._id)}>Delete</button></div></div></div></article>)}</div>}</section>{editing && <div className="modal-backdrop"><div className="modal"><ExpenseForm expense={editing.new ? null : editing} wallets={wallets} onSubmit={save} onCancel={close} /></div></div>}</>
}

function CategoryIcon({ category }) { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={{ Food: 'M5 4v16M5 4c2 2 2 5 0 7M9 4v16M19 4v16M15 4c-2 4-2 7 4 7', Transportation: 'M5 16h14l-1-6H6l-1 6Zm3 0v2m8-2v2M7 10l1-3h8l1 3', Shopping: 'M5 8h14l-1 11H6L5 8Zm4 0a3 3 0 0 1 6 0', Bills: 'M7 3h10v18H7zM10 7h4M10 11h4M10 15h4', Entertainment: 'm5 8 2 10h10l2-10-4 3-3-4-3 4-4-3Zm7 9v2', Health: 'M12 20S4 15 4 9a4 4 0 0 1 8-2 4 4 0 0 1 8 2c0 6-8 11-8 11Z', Education: 'm4 7 8-4 8 4-8 4-8-4Zm3 3v5c3 2 7 2 10 0v-5', Other: 'M12 3v18M3 12h18' }[category] || 'M12 3v18M3 12h18' } /></svg> }
